### ISSUE TITLE
Attribute 'GPUFanControlState' is not available

### ISSUE THREAD

**Issue by civyshk** [civyshk/nvidiafancurve#1]
The program fails to enable coolbits. In particular, the command `nvidia-settings -q GPUFanControlState` outputs:
> Attribute 'GPUFanControlState' specified in query 'GPUFanControlState' is not available on blah blah

So `nvidia-settings -a GPUFanControlState=1` doesn't work either. Recent driver update might be the cause. Both 384 & 381 don't work.

**Comment by nan0s7** [comment]
In 381.22 my script still works fine. I use the command `nvidia-settings -a "[gpu:0]/GPUFanControlState=1"` - but I don't know if it was changed in a later version. :D

**Comment by civyshk** [comment]
So it seems it's not related to driver version. I can't remember what has changed in my system, it used to work :$ .

**Comment by nan0s7** [comment]
I dunno how you enabled Coolbits (note; enabling fan-speed-control is not actually enabling _Coolbits_ itself, it's just enabling an option Coolbits gives you control of), but if you just added a line in your xorg.conf file, and you updated your drivers for your GPU, then it would have reverted to having Coolbits turned off after a reboot. If you use the extra config file in xorg.conf.d then that'll persist after an update.

**Comment by civyshk** [comment]
> note; enabling fan-speed-control is not actually enabling Coolbits itself

Thanks, that solved my problem. I had forgotten that the important setting was inside xorg.conf, which was overriden by a recent driver update. For the record:

```
Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Coolbits" "4"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```
And a bit of useful info for coolbits:

> When “1” (Bit 0) is set in the “Coolbits” option value, the nvidia-settings utility will contain a page labeled “Clock Frequencies” through which clock settings can be manipulated. “Coolbits” is only available on GeForce FX, Quadro FX and newer desktop GPUs. On GeForce FX and newer mobile GPUs, limited clock manipulation support is available when “1” is set in the “Coolbits” option value: clocks can be lowered relative to the default settings; overclocking is not supported due to the thermal constraints of notebook designs.

> When “2” (Bit 1) is set in the “Coolbits” option value, the NVIDIA driver will attempt to initialize SLI when using GPUs with different amounts of video memory.

> When “4” (Bit 2) is set in the “Coolbits” option value, the nvidia-settings Thermal Monitor page will allow configuration of GPU fan speed, on graphics boards with programmable fan capability.
The default for this option is 0 (unsupported features are disabled).

So now I'll rename things in my code to make clear that _coolbits_ is not _GPUFanControlState_.
